#version 450

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout (binding = 1, rgba32f) uniform writeonly image2D outputImage;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = vec4(0);
    ivec2 imgSize = imageSize(outputImage);
    if ((coord.x - 0.5 * imgSize.x) * (coord.x - 0.5 * imgSize.x) + (coord.y - 0.5 * imgSize.y) * (coord.y - 0.5 * imgSize.y) <= (0.25 * imgSize.x) * (0.25 * imgSize.x)) {
        color = vec4(1);
    }
    imageStore(outputImage, coord, color);
}